### ISSUE TITLE
icon size dimensions

### ISSUE THREAD

**Issue by jacobabey1** [fahrirusliyadi/fr-custom-payment-gateway-icon-for-woocommerce#1]
Which line of code , will allow you to adjust  the icon dimension or pick the default size of the image uploaded.

the icon uploaded is very small , need help to adjust the icon sizes

**Comment by fahrirusliyadi** [comment]
This plugin does not define the icon size. It's up to you to use any size you want. Also themes may use CSS to change the image dimension.

**Comment by jacobabey1** [comment]
Well noted and thanks ,its working as expected :)

**Comment by fahrirusliyadi** [comment]
You’re welcome :slightly_smiling_face:
